### PR TITLE
Update shadow-credentials.md

### PR DESCRIPTION
**Pull request by mpgn**

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Thank you for this PR, however, computer objects **can** edit their own KCL attribute. Only if it isn't set already though

**Comment by mpgn** [comment]
can edit if it isn't set already is the definition of "can only add" :)

**Comment by mpgn** [comment]
but i see what you mean but the wording :)

**Comment by ShutdownRepo** [comment]
I understand what you mean, let's reword it like, "can only edit if not set already/empty"

**Comment by mpgn** [comment]
Good for me !

**Review by ShutdownRepo — APPROVED** [review]

**Pull request merged**
