### PR TITLE
Add DCShadow

### PR DESCRIPTION
**Pull request by nuts7**
This commit add DCShadow explaination & commands.
Please feel free to make changes for potential errors or lack of information from my PR. 😃

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
I need to put this PR on hold, as we are in the process of reviewing a previous addition regarding DCShadow, I will then get back here to see if we can merge a few things. Thank you though for this great contribution proposal!

**Comment by ShutdownRepo** [comment]
@nuts7 the initial DC Shadow work has finally been merged, do you mind updating your PR to keep the information you think is missing from the page and would like to see added?

**Comment by ShutdownRepo** [comment]
Closing this PR due to inactivity, feel free to re-open if needed

**Comment by nuts7** [comment]
Much better than what I wrote, nothing to add thank you ^^

**Pull request closed without merging**
